name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Node
        uses: actions/setup-node@v1
          with:
              node-version: 12.8
              
      - run: npm run build:prod
      - run: npm run test:prod